function cqq = cQQ_matern_1(u1, v1, nu, a1, a2, coeffs, strength)
% Version of cQQ_matern for sensitivity analysis

u1 = reshape(u1, length(u1), 1);
v1 = reshape(v1, length(v1), 1);
[u1w1, u1w2] = W(u1, strength, a1, a2, coeffs); 
[v1w1, v1w2] = W(v1, strength, a1, a2, coeffs);

cqq = QQ_matern(u1, v1, nu) - ...
    repmat(v1w1', length(u1), 1) .* QQ_matern(u1, zeros(size(v1))+a1, nu) - ...
    repmat(v1w2', length(u1), 1) .* QQ_matern(u1, zeros(size(v1))+a2, nu) - ...
    repmat(u1w1, 1, length(v1)) .* QQ_matern(v1, zeros(size(u1))+a1, nu)' + ...
    repmat(u1w1, 1, length(v1)) .* repmat(v1w1', length(u1), 1) .* QQ_matern(zeros(size(u1))+a1, zeros(size(v1))+a1, nu) + ...
    repmat(u1w1, 1, length(v1)) .* repmat(v1w2', length(u1), 1) .* QQ_matern(zeros(size(u1))+a1, zeros(size(v1))+a2, nu) - ...
    repmat(u1w2, 1, length(v1)) .* QQ_matern(v1, zeros(size(u1))+a2, nu)' + ...
    repmat(u1w2, 1, length(v1)) .* repmat(v1w1', length(u1), 1) .* QQ_matern(zeros(size(u1))+a2, zeros(size(v1))+a1, nu) + ...
    repmat(u1w2, 1, length(v1)) .* repmat(v1w2', length(u1), 1) .* QQ_matern(zeros(size(u1))+a2, zeros(size(v1))+a2, nu);

end

